Cisim2018
fiji-hpc/scijava-parallel pull request #3
Opened 2018-04-11 13:07 UTC by kozusznik

2018-04-12 13:58 UTC, PetrBainar commented on cluster-scripts/run-imagej.sh
> +
Consider adding a brief description what this script is for.

In addition, consider renaming the file to e.g. run-imagej-server.sh.

2018-04-13 10:32 UTC, PetrBainar requested changes
Review finished apart from the ImageJ Server paradigm and worker.

2018-04-13 10:32 UTC, PetrBainar commented on cluster-scripts/run-local.sh
> +mvn exec:java -Dexec.mainClass="cz.it4i.parallel.TestSuite2" -Dexec.args="-l $COUNTS $STEP $NUMBER_OF_THREADS"
If I am not mistaken, the TestSuite2 class no longer exists. Please edit the script accordingly.

2018-04-13 10:32 UTC, PetrBainar commented on cluster-scripts/run-imagej.sh
> +
Consider adding a brief description what this script is for.

In addition, consider renaming the file to e.g. run-imagej-server.sh in order to be more specific. Should you do this, edit run-workers.sh accordingly.

2018-04-13 10:32 UTC, PetrBainar commented on cluster-scripts/run-master.sh
> +mvn exec:java -Dexec.mainClass="cz.it4i.parallel.TestSuite2" -Dexec.args="$COUNTS $STEP $HOSTS"
If I am not mistaken, the TestSuite2 class no longer exists. Please edit the script accordingly.

2018-04-13 10:32 UTC, PetrBainar commented on pom.xml
> +		<main-class>cz.it4i.parallel.TestSuite2</main-class>
If I am not mistaken, the TestSuite2 class no longer exists.

2018-04-13 10:32 UTC, PetrBainar commented on src/main/java/cz/it4i/parallel/WorkerPool.java
> +	/*public void execute(ParallelWorker worker, String moduleId, Map<String, ?> map) {
Remove unused code, if it is not needed anymore.

2018-04-13 10:32 UTC, PetrBainar commented on pom.xml
> +		    <groupId>net.bytebuddy</groupId>
Are all those dependencies needed? For example, I cannot see a reference to any bytebuddy packages by performing a simple web page search.

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/DemonstrateParadigm.java
> +public class DemonstrateParadigm implements Command {
Consider renaming to a bit more specific class name, e.g. BenchmarkOstravaParadigms, RotationBenchmark, etc. The same applies to the menu path annotation.

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/DemonstrateParadigm.java
> +package test;
As this is a completely new file, consider performing Eclipse auto-formatting. This will reduce future pull request noise.

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/DemonstrateParadigm.java
> +			file = Files.newDirectoryStream(Paths.get("/tmp/input/"), p -> p.toString().endsWith(".png") || p.toString().endsWith(".jpg")).iterator()
Consider defining a constant for input and output subpaths.

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/DemonstrateParadigm.java
> +		try (BufferedWriter bw = Files.newBufferedWriter(Paths.get("result-TestSuite2.txt"), StandardOpenOption.APPEND,
Ideally, there could be a config file for both script and Java code files, so that there is only one place where the name for the result file is defined.

Do you think that this could be achievable within the scope of this PR?

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/DemonstrateParadigm.java
> +	private static int count = 10;
Consider renaming to something a bit more descriptive, e.g. repetitionCount etc.

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/Cisim2018PaperSnippet.java
> +package test;
As this is a completely new file, consider performing Eclipse auto-formatting. This will reduce future pull request noise.

2018-04-13 10:32 UTC, PetrBainar commented on src/test/java/test/Cisim2018PaperSnippet.java
> +		return Paths.get("/tmp/output/result_" + input.angle + suffix(input.dataset));
Consider defining a constant for input and output subpaths.

2018-04-13 10:32 UTC, PetrBainar commented on src/main/java/cz/it4i/parallel/SimpleOstravaParadigm.java
>  package cz.it4i.parallel;
Consider performing auto-formatting. I know it is a faff but I guess now it is the right time to do it as the file has been changed a lot.

2018-04-13 10:32 UTC, PetrBainar commented on src/main/java/cz/it4i/parallel/SimpleOstravaParadigm.java
> +	private ForkJoinPool pool;
Consider renaming to forkJoinPool to be consistent with the workerPool naming convention.

2018-04-13 11:02 UTC, kozusznik commented on cluster-scripts/run-local.sh
> +mvn exec:java -Dexec.mainClass="cz.it4i.parallel.TestSuite2" -Dexec.args="-l $COUNTS $STEP $NUMBER_OF_THREADS"
solved

2018-04-23 11:36 UTC, merged

2018-04-24 07:41 UTC, kozusznik commented on src/test/java/test/Cisim2018PaperSnippet.java
> +package test;
done

2018-04-24 07:44 UTC, kozusznik commented on src/test/java/test/Cisim2018PaperSnippet.java
> +		return Paths.get("/tmp/output/result_" + input.angle + suffix(input.dataset));
DONE

2018-04-24 07:44 UTC, kozusznik commented on src/main/java/cz/it4i/parallel/SimpleOstravaParadigm.java
>  package cz.it4i.parallel;
done

2018-04-24 08:05 UTC, kozusznik commented on src/test/java/test/DemonstrateParadigm.java
> +		try (BufferedWriter bw = Files.newBufferedWriter(Paths.get("result-TestSuite2.txt"), StandardOpenOption.APPEND,
done

2018-04-24 08:05 UTC, kozusznik commented on src/test/java/test/DemonstrateParadigm.java
> +			file = Files.newDirectoryStream(Paths.get("/tmp/input/"), p -> p.toString().endsWith(".png") || p.toString().endsWith(".jpg")).iterator()
done

2018-04-24 08:05 UTC, kozusznik commented on src/test/java/test/DemonstrateParadigm.java
> +package test;
done

2018-04-24 08:07 UTC, kozusznik commented on src/test/java/test/DemonstrateParadigm.java
> +public class DemonstrateParadigm implements Command {
done

2018-04-24 08:13 UTC, kozusznik commented on cluster-scripts/run-imagej.sh
> +
done

2018-04-24 08:24 UTC, kozusznik reviewed
Review done